trigger:
  - master  # or 'main' depending on your branch name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npx playwright install
      npx playwright test
    displayName: 'Install dependencies and run Playwright tests'
